Dev main offer
Wmaileq/bayan pull request #2
Opened 2018-09-01 17:48 UTC by stalker3343

test pullrekvest

2018-09-02 22:16 UTC, Wmaileq requested changes

2018-09-02 22:16 UTC, Wmaileq commented on src/index.html
> +            <div class="video-production__cont-img">
У нас нет блока video-production, это должно быть в контексте video-card

2018-09-02 22:16 UTC, Wmaileq commented on src/index.html
> +        <h2 class="product-tabs__heading">Производcтво продукции</h2>
Элемент никак не связан с блоком, заголовки нужно выделить в отдельный компонент: - .h2,

2018-09-02 22:16 UTC, Wmaileq commented on src/index.html
> +          <div class="main-offer__header">Стань представителем самого инновационого завода в Казахстане</div>
Лучше назвать heading, т.к. header - обычно верхняя часть чего-то, а heading - заголовок (minor)

2018-09-02 22:16 UTC, Wmaileq commented on src/index.html
> +          <div class="main__button-wrapper main-offer__button">
Элемент не отсюда(main__button-wrapper), моя вина, компонент button в данный момент не корректный

2018-09-02 22:16 UTC, Wmaileq commented on src/index.html
> +            <a href="#" class="main__hint">Узнать больше о заводе</a>
main-offer__hint

2018-09-02 22:16 UTC, Wmaileq commented on src/index.html
> +        <div class="feature">
Не понятен смысл выделения блока внутри блока, это либо iconset__wrapper либо использовать бутстраповские .row>.col-3*4

2018-09-02 22:16 UTC, Wmaileq commented on src/index.html
> +            <div class="feature__item">
Можно выделить в отдельный компонент значок с текстом, т.к. будет переиспользование на другой странице

2018-09-02 22:16 UTC, Wmaileq commented on src/scss/main-offer.scss
>  	margin-top: 164px;
Об этом я не говорил, но у самых главных блоков, которые вставляются непосредственно в документ и которые должны иметь внешнее позиционирование мы указываем только margin-bottom, margin-top используем только в случае отрицательного значения

2018-09-02 22:16 UTC, Wmaileq commented on src/scss/main-offer.scss
>  	background-size: cover;
bgs есть, а bg нет?

2018-09-02 22:16 UTC, Wmaileq commented on src/scss/main-offer.scss
> -		background: url("img/bgMain-offer.png") no-repeat left top;
Псевдоэлемент должен располагаться сразу у родителя, а не где-то далеко, так же тут не нужен псевдоэлемент, фон должен быть у самого блока

2018-09-02 22:16 UTC, Wmaileq commented on src/scss/main-offer.scss
>  			top: 26px;
Думаю стоит сделать картинку с текстом одним png файлом, чтобы легче было адаптировать

2018-09-02 22:16 UTC, Wmaileq commented on src/scss/main-offer.scss
> +.video-card{
отдельный файл

2018-09-02 22:16 UTC, Wmaileq commented on src/scss/main-offer.scss
> +	&__treug{
треугольник стремный

2018-09-03 06:36 UTC, stalker3343 commented on src/index.html
> +        <h2 class="product-tabs__heading">Производcтво продукции</h2>
А почему он блоке Наша продукция не выделен в отдельный компонент? Заголовки ж отдельным блоком должны быть чтобы их вставлять

2018-09-03 06:39 UTC, stalker3343 commented on src/index.html
> +            <div class="video-production__cont-img">
![default](https://user-images.githubusercontent.com/42894422/44971142-1d1c1880-af5d-11e8-8337-3607248c5bc5.png)

Этот блок на других станицах встречается. Его нужно отдельно делать

2018-09-03 06:43 UTC, stalker3343 commented on src/index.html
> +          <div class="main__button-wrapper main-offer__button">
У меня используется не отдельный компонент button а весь блок main__button-wrapper поэтому нужно его делать отдельным от контекста main__
![default](https://user-images.githubusercontent.com/42894422/44971297-b5b29880-af5d-11e8-89d5-7e94c12e8369.png)

2018-09-03 06:44 UTC, stalker3343 commented on src/index.html
> +            <a href="#" class="main__hint">Узнать больше о заводе</a>
У меня используется не отдельный компонент button а весь блок main__button-wrapper поэтому нужно его делать отдельным от контекста main__ 
![default](https://user-images.githubusercontent.com/42894422/44971348-e266b000-af5d-11e8-8187-c5a7a0acc716.png)

2018-09-03 06:45 UTC, stalker3343 commented on src/scss/main-offer.scss
>  	margin-top: 164px;
Тогда нужно для твоего блока "Наша продукция" margin botom прописать

2018-09-03 06:51 UTC, stalker3343 commented on src/scss/main-offer.scss
>  			top: 26px;
Там эффект при наведении должен быть. Мы наводим на жёлтый кружок и появляется текст-подсказка. Думаю реализовать такое если это будет одна картинка png не получится

2018-09-03 06:52 UTC, stalker3343 commented on src/scss/main-offer.scss
> +	&__treug{
Название класса плохое или способ создания?

2018-09-03 07:21 UTC, stalker3343 commented on src/scss/main-offer.scss
> -		background: url("img/bgMain-offer.png") no-repeat left top;
Тут такой фон что он залазит на другую секцию. Если я секции задам он обрезаться по краям секции будет. Он вообще сложный этот фон, тебе лучше ему самому поправить
![default](https://user-images.githubusercontent.com/42894422/44972771-11cbeb80-af63-11e8-81f9-46e7d1d71828.png)

2018-09-04 08:08 UTC, Wmaileq commented on src/index.html
> +            <div class="video-production__cont-img">
Окей, вынесем в компонент, назовем "media", например, ну или еще какое-нибудь название можно придумать, production вообще не понимаю что значит)

2018-09-04 08:17 UTC, Wmaileq commented on src/index.html
> +          <div class="main__button-wrapper main-offer__button">
Тут не нужно выделять это в какой-то отдельный компонент, лучше повториться все таки и создать новый элемент с скопированными стилями, button я должен доработать

2018-09-04 08:20 UTC, Wmaileq commented on src/scss/main-offer.scss
> -		background: url("img/bgMain-offer.png") no-repeat left top;
Это делается через отрицательный margin-top, ok я возьму

2018-09-04 08:21 UTC, Wmaileq commented on src/scss/main-offer.scss
>  			top: 26px;
Не думаю что это эффект при наведении, никто не будет наводить на эти кружки чтобы узнать, что это "пример продукции" :)

2018-09-04 08:21 UTC, Wmaileq commented on src/scss/main-offer.scss
> +	&__treug{
Треугольник) Сам его внешний вид, сравни с макетом)

2018-09-04 08:41 UTC, Wmaileq requested changes

2018-09-04 08:41 UTC, Wmaileq commented on src/index.html
> +    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
Убираем, если нужна какая-то свг графика, бери отдельные иконки и кидай в img/icons либо используй png т.к. дизайнер не предоставил svg

2018-09-04 08:41 UTC, Wmaileq commented on src/index.html
> +                <div class="video-card__play">
Это может быть частью блока priduction-img(media), просто в других случаях не будем добавлять этот элемент(когда плей не нужен)

2018-09-04 08:41 UTC, Wmaileq commented on src/index.html
> +        <h2 class="product-tabs__heading">“Здесь будет цитата обращения первого</br>лица компании из блока ниже”</h2>
quote__heading

2018-09-04 08:41 UTC, Wmaileq commented on src/index.html
> +        <div class="quote__container d-flex justify-content-center">
Из бутстрапа договорились использовать только сетку: .container .container-fluid, col offset (перепиши d-flex и jcc в  scss quote__container'а

2018-09-04 08:41 UTC, Wmaileq commented on src/index.html
> +                <div class="quote__abzac">
__paragraph, __text, но не abzac))

2018-09-04 08:41 UTC, Wmaileq commented on src/index.html
> +        <div class="news">
news и akcia - это одинаковые блоки

2018-09-04 08:41 UTC, Wmaileq commented on src/index.html
> +    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
Либо оставим пока что, но нужно вести список всех иконок, что использовали, чтобы потом долго не искать

2018-09-04 15:26 UTC, Wmaileq approved these changes

2018-09-04 15:27 UTC, merged