Dev about company tabs
Wmaileq/bayan pull request #3
Opened 2018-09-03 12:39 UTC by BECJlO

2018-09-04 08:04 UTC, Wmaileq requested changes

2018-09-04 08:04 UTC, Wmaileq commented on gulpfile.js
> +        scss: 'src/scss/**/*.scss',
сасс уже подключил строчкой ниже

2018-09-04 08:04 UTC, Wmaileq commented on src/about-company.html
> +  <section class="about-company-tabs">
Очень длинное название, давай просто about :)

2018-09-04 08:04 UTC, Wmaileq commented on src/about-company.html
> +        <div class="about-company-tabs__nav">
Навигацию табов вынесем в отдельный компонент .tabs, т.к. он часто встречается на сайте

2018-09-04 08:04 UTC, Wmaileq commented on src/about-company.html
> +          <span class="delimeter-dot">&#8226;</span>
Это должна быть часть компонента, но вообще лучше сделать через псевдоэлемент

2018-09-04 08:04 UTC, Wmaileq commented on src/scss/about-company-tabs.scss
> +    @media (max-width: 992px){
991

2018-09-04 08:04 UTC, Wmaileq commented on src/scss/about-company-tabs.scss
> +.about-company-tabs::before
псевдоэлемент должен быть сразу под родителем

2018-09-04 08:50 UTC, Wmaileq requested changes

2018-09-04 08:50 UTC, Wmaileq commented on src/about-company.html
> +            <div class="about-company-tabs__wrap-img">
Моя оплошность, этот компонент уже сделан, называться будет media, сам потом исправлю

2018-09-04 08:50 UTC, Wmaileq commented on src/about-company.html
> +  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
jquery подключим не с cdn а запакуем в сборку, возможно, если js'а получится немного, перепишу в native js

2018-09-04 08:50 UTC, Wmaileq commented on src/js/main.js
> +    var blockId = "#" + this.dataset.block;
Просто рекоммендация - используй let и const

2018-09-04 08:50 UTC, Wmaileq commented on src/scss/about-company-tabs.scss
> +  &__nav-item::after{
&:after

2018-09-04 08:50 UTC, Wmaileq commented on src/scss/about-company-tabs.scss
> +    font-family: 'SourceSansPro', sans-serif;
По умолчанию этот шрифт стоит

2018-09-04 08:50 UTC, Wmaileq commented on src/scss/about-company-tabs.scss
> +    font-family: 'SourceSansPro', sans-serif;
Тоже самое (см. 151)

2018-09-04 08:50 UTC, Wmaileq commented on src/scss/about-company-tabs.scss
> +.delimeter-dot{
Тут можно не выносить(писал в html про это), а если выносишь, то ограничь область видимости блоком

2018-09-05 07:54 UTC, BECJlO commented on src/about-company.html
> +          <span class="delimeter-dot">&#8226;</span>
изначально так и делал, но на ховер и при добавление класса актив, у пункта меняется цвет и у  псевдо елемента тоже а отменяться в стилях не хотелось, но сделаю как скажешь

2018-09-05 07:55 UTC, BECJlO commented on src/scss/about-company-tabs.scss
> +    @media (max-width: 992px){
поменял, но чего так?

2018-09-05 08:18 UTC, BECJlO commented on src/scss/about-company-tabs.scss
> +.about-company-tabs::before
+

2018-09-05 08:43 UTC, BECJlO commented on src/scss/about-company-tabs.scss
> +  &__nav-item::after{
+

2018-09-05 08:48 UTC, BECJlO commented on src/scss/about-company-tabs.scss
> +    font-family: 'SourceSansPro', sans-serif;
+

2018-09-05 09:39 UTC, closed without merging